CREATE TABLE IF NOT EXISTS AGENTS(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USERAGENT VARCHAR(600) NOT NULL
);
CREATE TABLE IF NOT EXISTS STORE(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Store_name VARCHAR(300) NOT NULL,
    Store_category VARCHAR(300) NOT NULL,
    DATE timestamp
);

CREATE TABLE IF NOT EXISTS CATEGORIES(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CATEGORY_LINK VARCHAR(300) NOT NULL,
    CATEGORY_NAME VARCHAR(300) NOT NULL
);
CREATE TABLE IF NOT EXISTS PAGES(
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PAGE_CATEGORY VARCHAR(300) NOT NULL,
    PAGE_LINK TEXT NOT NULL
);